name: keypage

services:
  keypage:
    image: keypage
    build: .
    container_name: keypage
    ports:
      - "9090:9090"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
